name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: generate server.tgz
        run: |
          sudo apt update && sudo apt install -y easy-rsa openvpn
          mkdir ${{github.workspace}}/easyrsa
          ln -s /usr/share/easy-rsa/* ${{github.workspace}}/easyrsa/
          cd ${{github.workspace}}/easyrsa/
          cp vars.example vars
          echo "set_var EASYRSA_ALGO \"ec\"" >> vars
          echo "set_var EASYRSA_DIGEST \"sha512\"" >> vars
          ./easyrsa init-pki
          ./easyrsa build-ca nopass <<< ""
          ./easyrsa gen-req server nopass <<< ""
          ./easyrsa sign-req server server <<< "yes"
          openvpn --genkey --secret ta.key
          mkdir ${{github.workspace}}/server/
          cd ${{github.workspace}}
          cp easyrsa/ta.key server/
          cp easyrsa/pki/private/server.key server/
          cp easyrsa/pki/issued/server.crt server/
          cp easyrsa/pki/ca.crt server/
          cp server.conf server/
          cd ${{github.workspace}}
          tar zcvf server.tgz -C ${{github.workspace}}/server/
      - name: base64 server.tgz
        run: base64 server.tgz
      - name: Prepare client file
        run: mkdir -p ${{github.workspace}}/client-configs/files
      - name: Generate 1.ovpn
        run: |
          cd ${{github.workspace}}/easyrsa
          ./easyrsa gen-req client1 <<< ""
          ./easyrsa sign-req client client1 <<< "yes"
          mkdir -p ${{github.workspace}}/client-configs/keys/
          cp pki/private/client1.key ${{github.workspace}}/client-configs/keys/
          cp pki/issued/client1.crt ${{github.workspace}}/client-configs/keys/
          cp pki/ca.crt ${{github.workspace}}/client-configs/keys/
          cp ta.key ${{github.workspace}}/client-configs/keys/
          cp ${{github.workspace}}/make_config.sh ${{github.workspace}}/client-configs/
          chmod 700 ${{github.workspace}}/client-configs/make_config.sh
          cd ${{github.workspace}}/client-configs
          echo "TODO: base.conf"
          ./make_config.sh client1
      - run: echo "This job's status is ${{ job.status }}."
