name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: install openvpn and easyrsa
        run: |
          sudo apt-get update && sudo apt-get install openvpn easy-rsa
      - name: generate keys and CA
        run: |
          sudo chmod 777 -R /etc/openvpn && \ 
          mkdir -p /etc/openvpn/easyrsa && \
          ln -s /usr/share/easy-rsa/* /etc/openvpn/easyrsa/ && \
          chmod 700 /etc/openvpn/easyrsa/ && \
          cd /etc/openvpn/easyrsa/ && \
          cp vars.example vars && \
          echo "set_var EASYRSA_ALGO 'ec'" >> vars && \
          echo "set_var EASYRSA_ALGO 'ec'" >> vars && \
          easyrsa init-pki && \
          easyrsa build-ca nopass && \
          easyrsa gen-req server nopass && \
          easyrsa sign-req server server && \
          openvpn --genkey --secret ta.key && \
          mkdir /etc/openvpn/server/ && \
          cp ta.key ../server/ && \
          cp ../pki/private/server.key ../server/ && \
          cp ../pki/issued/server.crt ../server/ && \
          cp ../pki/ca.crt ../server/
      - run: echo "This job's status is ${{ job.status }}."
