name: GitHub Actions Demo
on: [push]
env:
  c1: 'client1'
  c2: 'client2'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: generate server.tgz
        run: |
          sudo apt update && sudo apt install -y easy-rsa openvpn
          mkdir ${{github.workspace}}/easyrsa
          ln -s /usr/share/easy-rsa/* ${{github.workspace}}/easyrsa/
          cd ${{github.workspace}}/easyrsa/
          cp vars.example vars
          echo "set_var EASYRSA_ALGO \"ec\"" >> vars
          echo "set_var EASYRSA_DIGEST \"sha512\"" >> vars
          ./easyrsa init-pki
          ./easyrsa build-ca nopass <<< ""
          ./easyrsa gen-req server nopass <<< ""
          ./easyrsa sign-req server server <<< "yes"
          openvpn --genkey --secret ta.key
          mkdir ${{github.workspace}}/server/
          cd ${{github.workspace}}
          cp easyrsa/ta.key server/
          cp easyrsa/pki/private/server.key server/
          cp easyrsa/pki/issued/server.crt server/
          cp easyrsa/pki/ca.crt server/
          cp server.conf server/
          cd ${{github.workspace}}
          tar zcvf server.tgz -C ${{github.workspace}}/server/ .
      - name: Prepare client file
        run: |
          mkdir -p ${{github.workspace}}/client-configs/files
          cp ${{github.workspace}}/make_config.sh ${{github.workspace}}/client-configs/
          chmod 700 ${{github.workspace}}/client-configs/make_config.sh
          cp ${{github.workspace}}/base.conf ${{github.workspace}}/client-configs/
      - name: Generate 1.ovpn
        run: |
          cd ${{github.workspace}}/easyrsa
          ./easyrsa gen-req ${{env.c1}} nopass <<< ""
          ./easyrsa sign-req client ${{env.c1}} <<< "yes"
          mkdir -p ${{github.workspace}}/client-configs/keys/
          cp pki/private/${{env.c1}}.key ${{github.workspace}}/client-configs/keys/
          cp pki/issued/${{env.c1}}.crt ${{github.workspace}}/client-configs/keys/
          cp pki/ca.crt ${{github.workspace}}/client-configs/keys/
          cp ta.key ${{github.workspace}}/client-configs/keys/
          cd ${{github.workspace}}/client-configs
          ./make_config.sh ${{env.c1}}
      - name: Generate 2.ovpn
        run: |
          cd ${{github.workspace}}/easyrsa
          ./easyrsa gen-req ${{env.c2}} nopass <<< ""
          ./easyrsa sign-req client ${{env.c2}} <<< "yes"
          mkdir -p ${{github.workspace}}/client-configs/keys/
          cp pki/private/${{env.c2}}.key ${{github.workspace}}/client-configs/keys/
          cp pki/issued/${{env.c2}}.crt ${{github.workspace}}/client-configs/keys/
          cp pki/ca.crt ${{github.workspace}}/client-configs/keys/
          cp ta.key ${{github.workspace}}/client-configs/keys/
          cd ${{github.workspace}}/client-configs
          ./make_config.sh ${{env.c2}}
      - name: Show result
        run: |
          echo "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-"
          base64 -w 0 server.tgz
          echo
          echo "\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-"
          cat ${{github.workspace}}/client-configs/files/${{env.c1}}.ovpn
          echo "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-"
          cat ${{github.workspace}}/client-configs/files/${{env.c2}}.ovpn
      - run: echo "This job's status is ${{ job.status }}."
